import type { WeaponDefinition, WeaponId } from '../weapons/WeaponTypes';

/**
 * Declarative weapon definitions. Values are tuned for game feel, not for
 * matching real ballistic tables: recoil angles are radians, spread is a
 * cone half-angle in radians, velocities are m/s.
 */
export const WEAPON_DEFINITIONS: Record<WeaponId, WeaponDefinition> = {
  /**
   * M1911 — the Zombies starting pistol. Deliberately a sidearm: modest
   * torso damage but a strong headshot multiplier, light recoil, fast ADS
   * and a quick reload. Precise players stretch it through early rounds;
   * raw damage per magazine keeps it from competing with the box weapons.
   * Procedural view model (no GLB), finite 8 / 32 ammunition.
   */
  m1911: {
    id: 'm1911',
    name: 'M1911',
    fireModes: ['semi'],
    defaultFireMode: 'semi',
    rpm: 360,
    magazineSize: 8,
    reserveAmmo: 32,
    reloadTime: 1.6,
    boltAction: false,
    boltCycleTime: 0,
    scoped: false,
    damage: 30,
    headshotMultiplier: 2.5,
    recoil: {
      verticalKick: 0.011,
      horizontalKick: 0.003,
      horizontalBias: 0,
      kickVariance: 0.2,
      recoverySpeed: 12,
      recoveryDelay: 0.06,
      cameraShare: 0.5,
      adsRecoilMultiplier: 0.7,
    },
    spread: {
      hipBase: 0.008,
      adsBase: 0.0015,
      bloomPerShot: 0.002,
      maxBloom: 0.012,
      bloomRecovery: 0.08,
    },
    ads: { fov: 58, speed: 12, sensitivity: 0.75 },
    projectile: { muzzleVelocity: 260, gravity: 9.8, maxDistance: 200, drag: 0.08 },
    moveSpeedMultiplier: 1.04,
    equipTime: 0.28,
    audio: { volume: 0.45, duration: 0.07, lowpass: 4200, thump: 210 },
    view: {
      // No GLB: dedicated procedural pistol builder (see WeaponView).
      frame: 'pistol',
      hip: [0.19, -0.19, -0.36],
      ads: [0, 0, -0.26],
      sway: 0.85,
      bob: 1.05,
      visualRecoil: { kickImpulse: 0.7, pitchImpulse: 1.9, rollImpulse: 0.5, stiffness: 220, damping: 18 },
      scale: 1,
      bodyColor: 0x2b2e33,
      accentColor: 0x6e4a2f,
      barrelLength: 0.12,
      barrelRadius: 0.0085,
      receiverLength: 0.19,
      stockLength: 0,
      magazine: 'straight',
      optic: 'irons',
      sightHeight: 0.05,
      bulk: 0.75,
      reloadAnim: {
        style: 'pistol',
        magOut: 0.08,
        magDrop: 0.2,
        magIn: 0.44,
        magSeat: 0.6,
        charge: 0.68,
        chargeEnd: 0.94,
        magSize: [0.024, 0.095, 0.036],
        magColor: 0x23262b,
      },
    },
  },

  m4a1: {
    id: 'm4a1',
    name: 'M4A1',
    fireModes: ['auto', 'semi'],
    defaultFireMode: 'auto',
    rpm: 800,
    magazineSize: 30,
    reloadTime: 2.1,
    boltAction: false,
    boltCycleTime: 0,
    scoped: false,
    damage: 34,
    headshotMultiplier: 2,
    recoil: {
      verticalKick: 0.0105,
      horizontalKick: 0.0035,
      horizontalBias: 0,
      kickVariance: 0.25,
      recoverySpeed: 9,
      recoveryDelay: 0.08,
      cameraShare: 0.6,
      adsRecoilMultiplier: 0.75,
    },
    spread: {
      hipBase: 0.014,
      adsBase: 0.0025,
      bloomPerShot: 0.0018,
      maxBloom: 0.02,
      bloomRecovery: 0.03,
    },
    ads: { fov: 55, speed: 9, sensitivity: 0.7 },
    projectile: { muzzleVelocity: 880, gravity: 9.8, maxDistance: 400, drag: 0.04 },
    moveSpeedMultiplier: 1,
    equipTime: 0.35,
    audio: { volume: 0.5, duration: 0.08, lowpass: 3400, thump: 170 },
    view: {
      modelUrl: 'assets/weapons/m4a1/model.glb',
      modelLength: 0.84,
      modelYaw: Math.PI / 2,
      hip: [0.24, -0.22, -0.42],
      ads: [0, 0, -0.3],
      sway: 1,
      bob: 1,
      visualRecoil: { kickImpulse: 0.9, pitchImpulse: 1.6, rollImpulse: 0.5, stiffness: 180, damping: 16 },
      scale: 1,
      bodyColor: 0x3a3f45,
      accentColor: 0x23262b,
      barrelLength: 0.3,
      barrelRadius: 0.011,
      receiverLength: 0.24,
      stockLength: 0.2,
      magazine: 'straight',
      optic: 'irons',
      sightHeight: 0.075,
      bulk: 1,
      reloadAnim: {
        style: 'rifle',
        magOut: 0.1,
        magDrop: 0.24,
        magIn: 0.48,
        magSeat: 0.64,
        charge: 0.72,
        chargeEnd: 0.94,
        magSize: [0.045, 0.13, 0.055],
        magColor: 0x23262b,
      },
    },
  },

  ak47: {
    id: 'ak47',
    name: 'AK-47',
    fireModes: ['auto', 'semi'],
    defaultFireMode: 'auto',
    rpm: 600,
    magazineSize: 30,
    reloadTime: 2.4,
    boltAction: false,
    boltCycleTime: 0,
    scoped: false,
    damage: 40,
    headshotMultiplier: 2,
    recoil: {
      verticalKick: 0.016,
      horizontalKick: 0.0065,
      horizontalBias: 0.2,
      kickVariance: 0.3,
      recoverySpeed: 7.5,
      recoveryDelay: 0.1,
      cameraShare: 0.62,
      adsRecoilMultiplier: 0.8,
    },
    spread: {
      hipBase: 0.016,
      adsBase: 0.0035,
      bloomPerShot: 0.003,
      maxBloom: 0.035,
      bloomRecovery: 0.025,
    },
    ads: { fov: 55, speed: 8, sensitivity: 0.7 },
    projectile: { muzzleVelocity: 715, gravity: 9.8, maxDistance: 400, drag: 0.05 },
    moveSpeedMultiplier: 0.96,
    equipTime: 0.4,
    audio: { volume: 0.6, duration: 0.1, lowpass: 2600, thump: 130 },
    view: {
      modelUrl: 'assets/weapons/ak47/model.glb',
      modelLength: 0.88,
      modelYaw: -Math.PI / 2,
      hip: [0.25, -0.22, -0.44],
      ads: [0, 0, -0.3],
      sway: 1.05,
      bob: 1,
      visualRecoil: { kickImpulse: 1.25, pitchImpulse: 2.4, rollImpulse: 0.9, stiffness: 140, damping: 13 },
      scale: 1,
      bodyColor: 0x33302c,
      accentColor: 0x7a5230,
      barrelLength: 0.34,
      barrelRadius: 0.011,
      receiverLength: 0.25,
      stockLength: 0.22,
      magazine: 'curved',
      optic: 'irons',
      sightHeight: 0.07,
      bulk: 1.02,
      reloadAnim: {
        style: 'rock',
        magOut: 0.07,
        magDrop: 0.2,
        magIn: 0.44,
        magSeat: 0.6,
        charge: 0.68,
        chargeEnd: 0.92,
        magSize: [0.05, 0.15, 0.06],
        magColor: 0x2a2d31,
      },
    },
  },

  m60: {
    id: 'm60',
    name: 'M60',
    fireModes: ['auto'],
    defaultFireMode: 'auto',
    rpm: 550,
    magazineSize: 100,
    reloadTime: 5.8,
    boltAction: false,
    boltCycleTime: 0,
    scoped: false,
    damage: 32,
    headshotMultiplier: 2,
    recoil: {
      verticalKick: 0.019,
      horizontalKick: 0.009,
      horizontalBias: -0.1,
      kickVariance: 0.35,
      recoverySpeed: 6,
      recoveryDelay: 0.12,
      cameraShare: 0.68,
      adsRecoilMultiplier: 0.85,
    },
    spread: {
      hipBase: 0.02,
      adsBase: 0.006,
      bloomPerShot: 0.0045,
      maxBloom: 0.06,
      bloomRecovery: 0.02,
    },
    ads: { fov: 62, speed: 4, sensitivity: 0.8 },
    projectile: { muzzleVelocity: 850, gravity: 9.8, maxDistance: 500, drag: 0.05 },
    moveSpeedMultiplier: 0.82,
    equipTime: 0.55,
    audio: { volume: 0.65, duration: 0.11, lowpass: 2200, thump: 110 },
    view: {
      // No GLB available: enhanced procedural model (see ASSETS.md).
      hip: [0.28, -0.26, -0.52],
      ads: [0, 0, -0.34],
      sway: 0.7,
      bob: 0.8,
      visualRecoil: { kickImpulse: 1.5, pitchImpulse: 2.0, rollImpulse: 1.2, stiffness: 90, damping: 11 },
      scale: 1.05,
      bodyColor: 0x2e3134,
      accentColor: 0x44484d,
      barrelLength: 0.42,
      barrelRadius: 0.014,
      receiverLength: 0.3,
      stockLength: 0.22,
      magazine: 'box',
      optic: 'irons',
      sightHeight: 0.085,
      bulk: 1.35,
      reloadAnim: {
        style: 'belt',
        magOut: 0.04,
        magDrop: 0.12,
        coverOpen: 0.18,
        magIn: 0.34,
        magSeat: 0.48,
        coverClose: 0.68,
        charge: 0.76,
        chargeEnd: 0.92,
        magSize: [0.1, 0.11, 0.13],
        magColor: 0x3a3e42,
      },
    },
  },

  l96: {
    id: 'l96',
    name: 'L96',
    fireModes: ['semi'],
    defaultFireMode: 'semi',
    rpm: 60,
    magazineSize: 5,
    reloadTime: 3.4,
    boltAction: true,
    boltCycleTime: 1.35,
    scoped: true,
    damage: 150,
    headshotMultiplier: 3,
    recoil: {
      verticalKick: 0.045,
      horizontalKick: 0.004,
      horizontalBias: 0,
      kickVariance: 0.15,
      recoverySpeed: 5,
      recoveryDelay: 0.25,
      cameraShare: 0.85,
      adsRecoilMultiplier: 0.9,
    },
    spread: {
      hipBase: 0.02,
      adsBase: 0.0004,
      bloomPerShot: 0.004,
      maxBloom: 0.01,
      bloomRecovery: 0.02,
    },
    ads: { fov: 16, speed: 5, sensitivity: 0.35 },
    projectile: { muzzleVelocity: 900, gravity: 9.8, maxDistance: 600, drag: 0.03 },
    moveSpeedMultiplier: 0.9,
    equipTime: 0.5,
    audio: { volume: 0.85, duration: 0.28, lowpass: 1800, thump: 90 },
    view: {
      modelUrl: 'assets/weapons/l96/model.glb',
      modelLength: 1.15,
      modelYaw: Math.PI / 2,
      hip: [0.22, -0.23, -0.5],
      ads: [0, 0, -0.32],
      sway: 1.1,
      bob: 0.9,
      visualRecoil: { kickImpulse: 1.1, pitchImpulse: 3.2, rollImpulse: 1.0, stiffness: 110, damping: 15 },
      scale: 1.05,
      bodyColor: 0x3c4a38,
      accentColor: 0x272c25,
      barrelLength: 0.5,
      barrelRadius: 0.012,
      receiverLength: 0.26,
      stockLength: 0.24,
      magazine: 'internal',
      optic: 'scope',
      sightHeight: 0.095,
      bulk: 1.1,
      reloadAnim: {
        style: 'bolt',
        magOut: 0.08,
        magDrop: 0.22,
        magIn: 0.42,
        magSeat: 0.56,
        charge: 0.64,
        chargeEnd: 0.96,
        magSize: [0.05, 0.08, 0.06],
        magColor: 0x272c25,
      },
    },
  },

  /**
   * Ray Gun — original retro-futuristic homage to the classic zombies-mode
   * wonder weapon. Procedural view model, synthesized audio, visible energy
   * projectile with splash damage. Only registered in Zombies mode.
   */
  raygun: {
    id: 'raygun',
    name: 'RAY GUN',
    fireModes: ['semi'],
    defaultFireMode: 'semi',
    rpm: 140,
    magazineSize: 20,
    reloadTime: 2.8,
    boltAction: false,
    boltCycleTime: 0,
    scoped: false,
    damage: 150,
    headshotMultiplier: 1.5,
    energy: { projectileSpeed: 48, splashRadius: 2.5, splashDamage: 100, color: 0x63f2a4 },
    recoil: {
      verticalKick: 0.012,
      horizontalKick: 0.004,
      horizontalBias: 0,
      kickVariance: 0.2,
      recoverySpeed: 10,
      recoveryDelay: 0.06,
      cameraShare: 0.55,
      adsRecoilMultiplier: 0.8,
    },
    spread: {
      hipBase: 0.004,
      adsBase: 0.001,
      bloomPerShot: 0.001,
      maxBloom: 0.008,
      bloomRecovery: 0.05,
    },
    ads: { fov: 60, speed: 10, sensitivity: 0.8 },
    projectile: { muzzleVelocity: 48, gravity: 0, maxDistance: 80, drag: 0 },
    moveSpeedMultiplier: 1,
    equipTime: 0.4,
    audio: { volume: 0.5, duration: 0.22, lowpass: 4200, thump: 200, energy: true },
    view: {
      // No GLB: dedicated procedural Ray Gun builder (see WeaponView).
      energyColor: 0x63f2a4,
      hip: [0.22, -0.2, -0.4],
      ads: [0, 0, -0.28],
      sway: 0.9,
      bob: 1,
      visualRecoil: { kickImpulse: 0.7, pitchImpulse: 1.4, rollImpulse: 0.6, stiffness: 160, damping: 15 },
      scale: 1,
      bodyColor: 0x8f9aa4,
      accentColor: 0xb87333,
      barrelLength: 0.16,
      barrelRadius: 0.02,
      receiverLength: 0.2,
      stockLength: 0.06,
      magazine: 'internal',
      optic: 'irons',
      sightHeight: 0.07,
      bulk: 0.9,
      reloadAnim: {
        style: 'cell',
        magOut: 0.1,
        magDrop: 0.26,
        magIn: 0.48,
        magSeat: 0.62,
        // No charging handle: the charge window drives the energy spin-up.
        charge: 0.68,
        chargeEnd: 0.95,
        magSize: [0.048, 0.048, 0.048],
        magColor: 0x63f2a4,
      },
    },
  },
};

export const WEAPON_ORDER: readonly WeaponId[] = ['m4a1', 'ak47', 'm60', 'l96', 'm1911'];

/**
 * Zombies PRELOADS every weapon it can ever hand out — the M1911 starting
 * pistol plus the whole Mystery Box pool — so box rolls never touch the
 * network. This is NOT the slot list: the zombies inventory starts with
 * the M1911 alone (see ZombiesMode.startingInventory) and the Ray Gun is
 * only obtainable from the Mystery Box.
 */
export const ZOMBIES_WEAPON_PRELOAD: readonly WeaponId[] = [
  'm1911',
  'm4a1',
  'ak47',
  'm60',
  'l96',
  'raygun',
];
